# Generated by Django 2.2.3 on 2019-07-20 16:42

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='SEO URL'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='SEO URL')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('created', models.DateField(default=datetime.date(2019, 7, 20), verbose_name='Дата')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO: Ключевые слова (через запятую)')),
                ('seo_description', models.TextField(blank=True, max_length=200, verbose_name='SEO: Описание')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'unique_together': {('slug', 'name')},
            },
        ),
    ]
