# Generated by Django 2.2.3 on 2019-07-20 18:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190720_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, unique=True, verbose_name='Заголовок (рус)')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание (рус)')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='Заголовок (англ)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание (англ)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='SEO URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.Category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
