# Generated by Django 2.2.3 on 2019-07-20 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190720_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=200, upload_to='category', verbose_name='Изображение категории'),
            preserve_default=False,
        ),
    ]
