# Generated by Django 2.2.3 on 2019-07-20 19:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='product', verbose_name='Основное Изображение продукта')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (рус)')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание (рус)')),
                ('name_en', models.CharField(max_length=200, unique=True, verbose_name='Заголовок (англ)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание (англ)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='SEO URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
